// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxkrzpqkxxlhmepeslqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54a3J6cHFreHhsaG1lcGVzbHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MDIxMjgsImV4cCI6MjA0OTI3ODEyOH0.QxuLQ-u7FHKZgkyClkc6BJkh6TdbRj7ROb4hvROUteQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);